fixed conditional checks for arguments

diff --git a/checksum b/checksum
--- a/checksum
+++ b/checksum
@@ -1,18 +1,31 @@
 #!/bin/bash
 
+if [[ $# -eq 0 ]]; then
+	echo ""
+    echo "No arguments provided. Nothing to do here..."
+	echo ""
+	exit 1
+fi
+
+if [[ ! -e "$1" ]]; then
+	echo ""
+	echo "Error: provided file does not exist."
+	echo ""
+	exit 1
+fi
+
+if [[ -z "$2" ]]; then
+	echo ""
+	echo "Error: no sha1 checksum provided."
+	echo ""
+	exit 2
+fi
+
+
 sha1out=`sha1sum $1`
 sumArray=($sha1out)
 inFileSum=${sumArray[0]}
 
-if [ -n "$1" ]; then
-	echo "Error: no file provided"
-	exit 1
-fi
-
-if [ -n "$2" ]; then
-	echo "Error: no sha1 checksum provided"
-	exit 2
-fi
 
 if [[ "$inFileSum" == "$2" ]]; then
 	echo ""
